# Configuration Dependabot pour Python (Poetry) et Node.js (npm)
version: 2
updates:
  # 1. Configuration pour Node.js / npm
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"

  # 2. Configuration pour Python / Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
