language: python
python:
  - "3.6"
dist: xenial
sudo: required
cache:
  - pip
  - npm

before_install:
  - pip install -U pipenv
  - cd back

install:
  - pipenv install --dev --deploy

script:
  - black --check .
  - python manage.py test -v 2
