# Generated by Django 4.2.23 on 2025-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0014_auto_20220819_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="google_wallet_class_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Google Wallet class ID",
            ),
        ),
    ]
