# Generated by Django 4.2.23 on 2025-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0016_fix_wallet_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Event end date",
                null=True,
                verbose_name="End date",
            ),
        ),
        migrations.AddField(
            model_name="ticketevent",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Event start date",
                null=True,
                verbose_name="Start date",
            ), 
        ),
        migrations.AlterField(
            model_name="registration",
            name="wallet_token",
            field=models.CharField(max_length=32),
        ),
    ]
