# Generated by Django 4.2.23 on 2025-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0017_ticketevent_end_date_ticketevent_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="wallet_pass",
            field=models.FileField(
                blank=True,
                help_text="Fichier .pkpass généré automatiquement",
                null=True,
                upload_to="wallet_passes/",
                verbose_name="Apple Wallet Pass",
            ),
        ),
    ]
