# Generated by Django 4.2.23 on 2025-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0018_registration_apple_wallet_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the event location",
                max_length=255,
                null=True,
                verbose_name="Location name",
            ),
        ),
    ]
