# Generated by Django 4.2.23 on 2025-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0019_ticketevent_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="wallet_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo used in Google and Apple Wallet passes",
                null=True,
                upload_to="wallet_logos/",
                verbose_name="Wallet logo",
            ),
        ),
    ]
