# Generated by Django 4.2.23 on 2025-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0020_ticketevent_wallet_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="wallet_strip",
            field=models.ImageField(
                blank=True,
                help_text="Image used in Apple Wallet passes",
                null=True,
                upload_to="wallet_strips/",
                verbose_name="Wallet strip image",
            ),
        ),
    ]
