# Generated by Django 6.0.7 on 2026-08-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0021_ticketevent_wallet_strip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneraction",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="registrations.registration",
            ),
        ),
    ]
