# Generated by Django 6.0.7 on 2026-08-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0022_change_scanneraction_registration_on_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "google_sheet_url",
                    models.URLField(verbose_name="Google Sheet URL"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncs",
                        to="registrations.ticketcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync",
                "verbose_name_plural": "Syncs",
            },
        ),
    ]
