# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='registrations.Registration')),
            ],
        ),
    ]
