# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scan', 'Scan du code'), ('entrance', 'Entrée sur le site'), ('cancel', 'Annulation après le scan')], max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('invite', 'Invité'), ('participant', 'Participant'), ('volontaire', 'Volontaire')], max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre / Non défini')], max_length=1)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('ticket_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='registrations.Registration')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registrations.Registration'),
        ),
    ]
