# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scan', 'Scan du code'), ('entrance', 'Entrée sur le site'), ('cancel', 'Annulation après le scan')], max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registrations.Registration')),
            ],
        ),
    ]
