# Generated by Django 2.0.8 on 2018-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact_email',
            field=models.TextField(verbose_name='Emails de contact'),
        ),
    ]
