# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20171121_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='contact_email',
            field=models.EmailField(default='convention@lafranceinsoumise.fr', max_length=254, verbose_name='Email de contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre / Non défini')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Royer'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ticket_sent',
            field=models.BooleanField(default=False, verbose_name='Ticker envoyé'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(blank=True, choices=[('invite', 'Invité'), ('participant', 'Participant'), ('volontaire', 'Volontaire')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Identifiant sur la plateforme'),
        ),
    ]
