# Generated by Django 2.0.9 on 2018-12-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("registrations", "0003_auto_20180816_1225")]

    operations = [
        migrations.RemoveIndex(
            model_name="registrationmeta", name="registration_property_index"
        ),
        migrations.AlterUniqueTogether(
            name="registrationmeta", unique_together={("registration", "property")}
        ),
    ]
