# Generated by Django 2.2.4 on 2019-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registrations", "0004_auto_20181205_1602")]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="import_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Identifiant dans les fichiers d'import",
            ),
        )
    ]
