# Generated by Django 2.2.4 on 2019-08-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("registrations", "0005_ticketcategory_import_key")]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="_contact_emails",
            field=models.TextField(blank=True, verbose_name="Emails de contact"),
        )
    ]
