# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models


def populate_full_name(apps, schema_editor):
    Registration = apps.get_model('registrations', 'Registration')

    Registration.objects.update(full_name=models.F('first_name') + ' ' + models.F('last_name'))


def unpopulate_full_name(apps, schema_editor):
    Registration = apps.get_model('registrations', 'Registration')

    Registration.objects.update(full_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20171121_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom complet'),
        ),
        migrations.RunPython(code=populate_full_name, reverse_code=unpopulate_full_name),
    ]
