# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_registration_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nom complet'),
        ),
    ]
