# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20171121_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre / Non défini')], max_length=1, verbose_name='Genre'),
        ),
    ]
