# Generated by Django 2.0.4 on 2018-04-03 14:32

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def create_and_assign_legacy_events_and_categories(apps, schema_editor):
    TicketEvent = apps.get_model('registrations', 'TicketEvent')
    TicketCategory = apps.get_model('registrations', 'TicketCategory')
    Registration = apps.get_model('registrations', 'Registration')
    ticket_event = TicketEvent.objects.create(name="LegacyEvents", send_tickets_until=timezone.now())
    categories = {}

    for category in [
        ('invite', '#fff', '#272F6C'),
        ('participant', '#ddd', '#fff'),
        ('volontaire', '#fff', '#61C674'),
        ('volontaire_referent', '#fff', '#1C4E29'),
        ('village', '#fff', '#19B4C8'),
        ('so', '#fff', '#D73F24')
    ]:
        categories[category[0]] = TicketCategory.objects.create(name=category[0], color=category[1],
                                                                background_color=category[2], event=ticket_event)

    for registration in Registration.objects.all():
        registration.event = ticket_event
        registration.category = categories[registration.type]
        registration.save()


def rollback(apps, schema_editor):
    Registration = apps.get_model('registrations', 'Registration')
    for registration in Registration.objects.all():
        registration.type = registration.category.name
        registration.save()


class Migration(migrations.Migration):
    dependencies = [
        ('registrations', '0013_auto_20180403_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name="Nom de l'événement")),
                ('send_tickets_until', models.DateTimeField(verbose_name="Envoyé les tickets jusqu'à la date")),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom de la catégorie')),
                ('color', models.TextField(max_length=255, verbose_name='Couleur')),
                ('background_color', models.TextField(max_length=255, verbose_name='Couleur de fond')),
            ],
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.TicketEvent'),
        ),
        migrations.AddField(
            model_name='registration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='registrations.TicketCategory', null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='registrations.TicketEvent', null=True)
        ),
        migrations.RunPython(create_and_assign_legacy_events_and_categories, rollback),
        migrations.RemoveField(
            model_name='registration',
            name='type',
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='registrations.TicketCategory'),
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='registrations.TicketEvent')
        ),
    ]
