# Generated by Django 2.0.4 on 2018-04-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_auto_20180403_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='ScannerAction',
        ),
    ]
