# Generated by Django 2.0.4 on 2018-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20180403_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='background_color',
            field=models.CharField(max_length=255, verbose_name='Couleur de fond'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'événement"),
        ),
    ]
