# Generated by Django 2.0.4 on 2018-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_auto_20180403_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='table',
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='mosaico_url',
            field=models.URLField(blank=True, verbose_name='URL du mail sur Mosaico'),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='ticket_template',
            field=models.FileField(blank=True, upload_to='', verbose_name='Template du ticket'),
        ),
    ]
