# Generated by Django 2.0.4 on 2018-04-03 16:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('registrations', '0017_auto_20180403_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='numero',
            new_name='id',
        ),
    ]
