# Generated by Django 2.0.4 on 2018-04-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_auto_20180403_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketcategory',
            unique_together={('event', 'name')},
        ),
    ]
